src/EntityFrameworkExtraMile/Controllers/EmployeeController.cs
using System.Linq;
using System.Web.Mvc;
using EntityFrameworkExtraMile.Domain.Model;
using EntityFrameworkExtraMile.Infrastructure.DataAccess;

namespace EntityFrameworkExtraMile.Controllers
{
    public class EmployeeController : Controller
    {
        //
        // GET: /Employee/

        public ActionResult Index()
        {
            var context = new HumanResourceContext();

            var employees = context.Employees.ToArray();

            #region hide
            //var employees = context.Employees
            //           .Include(e => e.Address.State)
            //           .Include(e => e.PayrollDeductions)
            //           .Include(e => e.CompanyAssets)
            //           .ToArray();

            //var employees = context.Employees
            //                       .Include(e => e.Address.State)
            //                       .ToArray();

            //employees = context.Employees
            //       .Include(e => e.PayrollDeductions)
            //       .ToArray();

            //employees = context.Employees
            //       .Include(e => e.CompanyAssets)
            //       .ToArray();
            #endregion

            return View(employees);
        }

        public ActionResult Edit(int id)
        {
            var context = new HumanResourceContext();

            var employee = context.Employees.Find(id);

            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit(Employee model, int id)
        {
            var context = new HumanResourceContext();

            var employee = context.Employees.Find(id);
            employee.LastName = model.LastName;
            employee.FirstName = model.FirstName;
            employee.MiddleName = model.MiddleName;
            context.SaveChanges();
            //context.SaveChanges("mike");

            return RedirectToAction("Index");
        }
    }
}

src/EntityFrameworkExtraMile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>